spring.application.name=demo

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.njzkudfjrfdcrzfmjtfq
spring.datasource.password=nI=1u<76hLO$5B8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true